default_model = "gemini-2.5-pro-exp-03-25"

#[[models]]
#name = "openrouter/google/gemini-2.5-flash-preview"
#display_name = "Gemini 2.5 Pro"
#Eprovider = "openrouter"
#api_base = "https://openrouter.ai/api/v1"
#api_key = "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"
#theme = "nautilus"

[[models]]
name = "gemini/gemini-2.5-pro-exp-03-25"
display_name = "Gemini 2.5 Pro"
provider = "Google"
api_key = "AIzaSyAHCD5Y15aeqdqPR08t98Tjhpyt2ynccio"
theme = "nautilus"

[[models]]
name = "gemini/gemini-2.5-flash-preview-04-17"
display_name = "Gemini 2.5 Flash"
provider = "Google"
api_key = "AIzaSyAHCD5Y15aeqdqPR08t98Tjhpyt2ynccio"
theme = "nautilus"
